{{-- PDF Document Footer --}}
{{-- Required: $config array with keys: documentType, documentNumber --}}
@php
    $documentType = $config['documentType'] ?? 'Document';
    $documentNumber = $config['documentNumber'] ?? '';
@endphp

<div class="footer">
    <table>
        <tr>
            <td>
                <h4>Payment Information</h4>
                <p>
                    <span class="highlight">BSP Account</span><br>
                    Account Name: TZ Holding Limited<br>
                    Account #: 2001682364
                </p>
            </td>
            <td>
                <h4>Questions or Support</h4>
                <p>
                    Contact: Zefi<br>
                    Phone: +677 7799978<br>
                    Location: Honiara, Solomon Islands
                </p>
            </td>
        </tr>
    </table>

    <div class="generator">
        Generated by {{ config('app.name') }} • {{ $documentType }} {{ $documentNumber }}
    </div>
</div>
